spring:
  application:
    name: LibraryManagement

  datasource:
    url: jdbc:mysql://localhost:3306/library_management?createDatabaseIfNotExist=true
    username: root
    password: Bimsara1@Induwara2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate: ddl-auto=update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Server Configuration
server:
  port=8080

