spring:
  application:
    name: LibraryManagement

  datasource:
    url: jdbc:mysql://localhost:3306/library_management?createDatabaseIfNotExist=true
    username: root
    password: Bimsara1@Induwara2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # CORS Configuration
  web:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,X-Requested-With
      allow-credentials: true

# Server Configuration
server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: 9a4f2c8d3b7a1e6f4c8d2a5f6v8a9d4s2d5f8a7s9d8f7a9s8f7d9a8s7f9a8s7d
    expirationMs: 86400000 # 24 hours

# Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    com.induwara.librarymanagement: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.cors: TRACE

